# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterFaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 843)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 30, 900, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(900, 650))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-top-left-radius:20px;\n"
"border-bottom:0px solid rgba(4, 135, 206,100);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(20, 10, 25, 25))
        self.label.setMinimumSize(QtCore.QSize(25, 25))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/phres/icon/logintopleft.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(60, 1, 181, 41))
        self.label_2.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame3button = QtWidgets.QFrame(self.frame_2)
        self.frame3button.setMinimumSize(QtCore.QSize(200, 0))
        self.frame3button.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"}")
        self.frame3button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame3button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame3button.setObjectName("frame3button")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame3button)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonBack = QtWidgets.QPushButton(self.frame3button)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonBack.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/phres/icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.horizontalLayout_4.addWidget(self.pushButtonBack)
        self.pushButtonMin = QtWidgets.QPushButton(self.frame3button)
        self.pushButtonMin.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonMin.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/phres/icon/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMin.setIcon(icon1)
        self.pushButtonMin.setObjectName("pushButtonMin")
        self.horizontalLayout_4.addWidget(self.pushButtonMin)
        self.pushButtonClose = QtWidgets.QPushButton(self.frame3button)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButtonClose.setStyleSheet("#pushButtonClose{\n"
"border-top-right-radius:16px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgba(255, 0, 0,180);\n"
"    icon-color:white\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgba(255, 0, 0,130);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}")
        self.pushButtonClose.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/phres/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon2)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_4.addWidget(self.pushButtonClose)
        self.horizontalLayout_3.addWidget(self.frame3button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color:rgb(4, 135, 206);\n"
"border-bottom-left-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    border-bottom:1px solid rgba(197, 197, 197,100);\n"
"    background-color:rgb(4, 135, 206);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 25 15pt \"微软雅黑 Light\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"    background-color: rgba(12, 198, 255,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(12, 198, 255,200);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(10, 15, 10, 15)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonHome = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonHome.setEnabled(True)
        self.pushButtonHome.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/phres/icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHome.setIcon(icon3)
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.verticalLayout_2.addWidget(self.pushButtonHome)
        self.pushButtonCard = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonCard.setObjectName("pushButtonCard")
        self.verticalLayout_2.addWidget(self.pushButtonCard)
        self.pushButtonEvent = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonEvent.setObjectName("pushButtonEvent")
        self.verticalLayout_2.addWidget(self.pushButtonEvent)
        self.pushButtonSug = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonSug.setObjectName("pushButtonSug")
        self.verticalLayout_2.addWidget(self.pushButtonSug)
        self.pushButtonWeb = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonWeb.setObjectName("pushButtonWeb")
        self.verticalLayout_2.addWidget(self.pushButtonWeb)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButtonMe = QtWidgets.QPushButton(self.frame_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/phres/icon/me.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMe.setIcon(icon4)
        self.pushButtonMe.setObjectName("pushButtonMe")
        self.verticalLayout_2.addWidget(self.pushButtonMe)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color: rgb(255, 255, 255);\n"
"border-bottom-right-radius:20px;\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("QPushButton{\n"
"    border-radius:8px;\n"
"    font: 10pt \"幼圆\";\n"
"    background-color: rgba(0, 170, 255,80);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(0, 170, 255,125);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.label_3 = QtWidgets.QLabel(self.pageHome)
        self.label_3.setGeometry(QtCore.QRect(54, 20, 101, 31))
        self.label_3.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.label_25 = QtWidgets.QLabel(self.pageHome)
        self.label_25.setGeometry(QtCore.QRect(24, 24, 24, 24))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/icon/phres/icon/homepage.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.frame_8 = QtWidgets.QFrame(self.pageHome)
        self.frame_8.setGeometry(QtCore.QRect(30, 50, 401, 401))
        self.frame_8.setStyleSheet("border-radius:5px")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.labelFigure1 = QtWidgets.QLabel(self.frame_8)
        self.labelFigure1.setGeometry(QtCore.QRect(20, 40, 350, 350))
        self.labelFigure1.setStyleSheet("border:none;")
        self.labelFigure1.setText("")
        self.labelFigure1.setScaledContents(True)
        self.labelFigure1.setObjectName("labelFigure1")
        self.label_23 = QtWidgets.QLabel(self.frame_8)
        self.label_23.setGeometry(QtCore.QRect(160, 20, 81, 20))
        self.label_23.setStyleSheet("font: 9pt \"幼圆\";")
        self.label_23.setObjectName("label_23")
        self.frame_9 = QtWidgets.QFrame(self.pageHome)
        self.frame_9.setGeometry(QtCore.QRect(440, 50, 281, 271))
        self.frame_9.setStyleSheet("border-radius:5px")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lineEditHE2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHE2.setGeometry(QtCore.QRect(10, 120, 113, 20))
        self.lineEditHE2.setObjectName("lineEditHE2")
        self.label_37 = QtWidgets.QLabel(self.frame_9)
        self.label_37.setGeometry(QtCore.QRect(50, 50, 51, 20))
        self.label_37.setStyleSheet("font: 9pt \"幼圆\";")
        self.label_37.setObjectName("label_37")
        self.label_36 = QtWidgets.QLabel(self.frame_9)
        self.label_36.setGeometry(QtCore.QRect(110, 20, 51, 20))
        self.label_36.setStyleSheet("font: 9pt \"幼圆\";")
        self.label_36.setObjectName("label_36")
        self.lineEditHT2 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHT2.setGeometry(QtCore.QRect(160, 120, 113, 20))
        self.lineEditHT2.setObjectName("lineEditHT2")
        self.lineEditHT4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHT4.setGeometry(QtCore.QRect(160, 200, 113, 20))
        self.lineEditHT4.setObjectName("lineEditHT4")
        self.lineEditHE1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHE1.setGeometry(QtCore.QRect(10, 80, 113, 20))
        self.lineEditHE1.setObjectName("lineEditHE1")
        self.lineEditHT1 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHT1.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.lineEditHT1.setObjectName("lineEditHT1")
        self.lineEditHT3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHT3.setGeometry(QtCore.QRect(160, 160, 113, 20))
        self.lineEditHT3.setObjectName("lineEditHT3")
        self.lineEditHE3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHE3.setGeometry(QtCore.QRect(10, 160, 113, 20))
        self.lineEditHE3.setObjectName("lineEditHE3")
        self.label_38 = QtWidgets.QLabel(self.frame_9)
        self.label_38.setGeometry(QtCore.QRect(200, 50, 51, 20))
        self.label_38.setStyleSheet("font: 9pt \"幼圆\";")
        self.label_38.setObjectName("label_38")
        self.lineEditHE4 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditHE4.setGeometry(QtCore.QRect(10, 200, 113, 20))
        self.lineEditHE4.setObjectName("lineEditHE4")
        self.stackedWidget.addWidget(self.pageHome)
        self.pageCard = QtWidgets.QWidget()
        self.pageCard.setObjectName("pageCard")
        self.label_4 = QtWidgets.QLabel(self.pageCard)
        self.label_4.setGeometry(QtCore.QRect(54, 20, 101, 31))
        self.label_4.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_4.setObjectName("label_4")
        self.pushButtonAdd = QtWidgets.QPushButton(self.pageCard)
        self.pushButtonAdd.setGeometry(QtCore.QRect(550, 90, 32, 32))
        self.pushButtonAdd.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pushButtonAdd.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/phres/icon/user-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAdd.setIcon(icon5)
        self.pushButtonAdd.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonDP = QtWidgets.QPushButton(self.pageCard)
        self.pushButtonDP.setGeometry(QtCore.QRect(590, 90, 32, 32))
        self.pushButtonDP.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pushButtonDP.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/phres/icon/user-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDP.setIcon(icon6)
        self.pushButtonDP.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonDP.setObjectName("pushButtonDP")
        self.tabWidgetCard = QtWidgets.QTabWidget(self.pageCard)
        self.tabWidgetCard.setGeometry(QtCore.QRect(20, 100, 701, 471))
        self.tabWidgetCard.setMinimumSize(QtCore.QSize(500, 400))
        self.tabWidgetCard.setStyleSheet("#tabWidget{\n"
"border:3px solid blue;\n"
"}\n"
"")
        self.tabWidgetCard.setObjectName("tabWidgetCard")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    border-radius:0px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.tabWidgetCard.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidgetP = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetP.setGeometry(QtCore.QRect(9, 9, 677, 428))
        self.tableWidgetP.setObjectName("tableWidgetP")
        self.tableWidgetP.setColumnCount(0)
        self.tableWidgetP.setRowCount(0)
        self.tabWidgetCard.addTab(self.tab_2, "")
        self.pushButtonPRefresh = QtWidgets.QPushButton(self.pageCard)
        self.pushButtonPRefresh.setGeometry(QtCore.QRect(670, 90, 32, 32))
        self.pushButtonPRefresh.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pushButtonPRefresh.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/phres/icon/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPRefresh.setIcon(icon7)
        self.pushButtonPRefresh.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonPRefresh.setObjectName("pushButtonPRefresh")
        self.pushButtonSearch = QtWidgets.QPushButton(self.pageCard)
        self.pushButtonSearch.setGeometry(QtCore.QRect(630, 90, 32, 32))
        self.pushButtonSearch.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pushButtonSearch.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/phres/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSearch.setIcon(icon8)
        self.pushButtonSearch.setIconSize(QtCore.QSize(28, 28))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.stackedWidget_4 = QtWidgets.QStackedWidget(self.pageCard)
        self.stackedWidget_4.setGeometry(QtCore.QRect(180, 40, 321, 61))
        self.stackedWidget_4.setStyleSheet("font: 12pt \"幼圆\";")
        self.stackedWidget_4.setObjectName("stackedWidget_4")
        self.page0 = QtWidgets.QWidget()
        self.page0.setObjectName("page0")
        self.stackedWidget_4.addWidget(self.page0)
        self.page1delete = QtWidgets.QWidget()
        self.page1delete.setObjectName("page1delete")
        self.label_16 = QtWidgets.QLabel(self.page1delete)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page1delete)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 19, 161, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgba(209, 209, 209,50);\n"
"border:none;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButtonDe = QtWidgets.QPushButton(self.page1delete)
        self.pushButtonDe.setGeometry(QtCore.QRect(280, 18, 28, 28))
        self.pushButtonDe.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pushButtonDe.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/phres/icon/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDe.setIcon(icon9)
        self.pushButtonDe.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDe.setObjectName("pushButtonDe")
        self.stackedWidget_4.addWidget(self.page1delete)
        self.page2search = QtWidgets.QWidget()
        self.page2search.setObjectName("page2search")
        self.label_22 = QtWidgets.QLabel(self.page2search)
        self.label_22.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_22.setObjectName("label_22")
        self.lineEditSearch = QtWidgets.QLineEdit(self.page2search)
        self.lineEditSearch.setGeometry(QtCore.QRect(110, 19, 161, 20))
        self.lineEditSearch.setStyleSheet("background-color: rgba(209, 209, 209,50);\n"
"border:none;")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButtonSe = QtWidgets.QPushButton(self.page2search)
        self.pushButtonSe.setGeometry(QtCore.QRect(280, 18, 28, 28))
        self.pushButtonSe.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166,100);\n"
"    border-bottom:1px solid rgba(166, 166, 166,100);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(166, 166, 166,160);\n"
"    padding-left:3px;\n"
"    padding-top:3px\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    \n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.pushButtonSe.setText("")
        self.pushButtonSe.setIcon(icon9)
        self.pushButtonSe.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSe.setObjectName("pushButtonSe")
        self.stackedWidget_4.addWidget(self.page2search)
        self.label_24 = QtWidgets.QLabel(self.pageCard)
        self.label_24.setGeometry(QtCore.QRect(24, 24, 24, 24))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/icon/phres/icon/list.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_4.raise_()
        self.tabWidgetCard.raise_()
        self.pushButtonAdd.raise_()
        self.pushButtonDP.raise_()
        self.pushButtonPRefresh.raise_()
        self.pushButtonSearch.raise_()
        self.stackedWidget_4.raise_()
        self.label_24.raise_()
        self.stackedWidget.addWidget(self.pageCard)
        self.pageEvent = QtWidgets.QWidget()
        self.pageEvent.setObjectName("pageEvent")
        self.label_5 = QtWidgets.QLabel(self.pageEvent)
        self.label_5.setGeometry(QtCore.QRect(54, 20, 101, 31))
        self.label_5.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_5.setObjectName("label_5")
        self.label_29 = QtWidgets.QLabel(self.pageEvent)
        self.label_29.setGeometry(QtCore.QRect(24, 24, 24, 24))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/icon/phres/icon/eventlist.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.pageEvent)
        self.label_30.setGeometry(QtCore.QRect(24, 438, 24, 24))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap(":/icon/phres/icon/添加增加加入.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.pageEvent)
        self.label_31.setGeometry(QtCore.QRect(54, 440, 91, 20))
        self.label_31.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.pageEvent)
        self.label_32.setGeometry(QtCore.QRect(40, 470, 71, 21))
        self.label_32.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.pageEvent)
        self.label_33.setGeometry(QtCore.QRect(40, 500, 71, 21))
        self.label_33.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.pageEvent)
        self.label_34.setGeometry(QtCore.QRect(420, 500, 71, 21))
        self.label_34.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.pageEvent)
        self.label_35.setGeometry(QtCore.QRect(230, 500, 71, 21))
        self.label_35.setStyleSheet("font: 12pt \"幼圆\";")
        self.label_35.setObjectName("label_35")
        self.lineEditEventDescribe = QtWidgets.QLineEdit(self.pageEvent)
        self.lineEditEventDescribe.setGeometry(QtCore.QRect(112, 470, 331, 23))
        self.lineEditEventDescribe.setStyleSheet("border:1px solid rgb(202, 202, 202)")
        self.lineEditEventDescribe.setObjectName("lineEditEventDescribe")
        self.lineEditEventMember = QtWidgets.QLineEdit(self.pageEvent)
        self.lineEditEventMember.setGeometry(QtCore.QRect(80, 500, 141, 23))
        self.lineEditEventMember.setStyleSheet("border:1px solid rgb(202, 202, 202)")
        self.lineEditEventMember.setObjectName("lineEditEventMember")
        self.lineEditEventTime = QtWidgets.QLineEdit(self.pageEvent)
        self.lineEditEventTime.setGeometry(QtCore.QRect(270, 500, 141, 23))
        self.lineEditEventTime.setStyleSheet("border:1px solid rgb(202, 202, 202)")
        self.lineEditEventTime.setObjectName("lineEditEventTime")
        self.lineEditEventPlace = QtWidgets.QLineEdit(self.pageEvent)
        self.lineEditEventPlace.setGeometry(QtCore.QRect(460, 500, 131, 23))
        self.lineEditEventPlace.setStyleSheet("border:1px solid rgb(202, 202, 202)")
        self.lineEditEventPlace.setObjectName("lineEditEventPlace")
        self.pushButtonEventAdd = QtWidgets.QPushButton(self.pageEvent)
        self.pushButtonEventAdd.setGeometry(QtCore.QRect(570, 540, 75, 23))
        self.pushButtonEventAdd.setObjectName("pushButtonEventAdd")
        self.tableWidgetEvent = QtWidgets.QTableWidget(self.pageEvent)
        self.tableWidgetEvent.setGeometry(QtCore.QRect(30, 70, 681, 361))
        self.tableWidgetEvent.setStyleSheet("border:1px solid rgb(202, 202, 202)")
        self.tableWidgetEvent.setObjectName("tableWidgetEvent")
        self.tableWidgetEvent.setColumnCount(0)
        self.tableWidgetEvent.setRowCount(0)
        self.stackedWidget.addWidget(self.pageEvent)
        self.pageSug = QtWidgets.QWidget()
        self.pageSug.setObjectName("pageSug")
        self.label_6 = QtWidgets.QLabel(self.pageSug)
        self.label_6.setGeometry(QtCore.QRect(54, 20, 101, 31))
        self.label_6.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_6.setObjectName("label_6")
        self.label_26 = QtWidgets.QLabel(self.pageSug)
        self.label_26.setGeometry(QtCore.QRect(24, 24, 24, 24))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/icon/phres/icon/advicepage.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.frame_11 = QtWidgets.QFrame(self.pageSug)
        self.frame_11.setGeometry(QtCore.QRect(30, 60, 671, 501))
        self.frame_11.setStyleSheet("font: 14pt \"幼圆\";")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_45 = QtWidgets.QLabel(self.frame_11)
        self.label_45.setGeometry(QtCore.QRect(40, 40, 81, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.frame_11)
        self.label_46.setGeometry(QtCore.QRect(150, 40, 501, 31))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_11)
        self.label_47.setGeometry(QtCore.QRect(40, 80, 91, 31))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.frame_11)
        self.label_48.setGeometry(QtCore.QRect(150, 80, 501, 31))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.frame_11)
        self.label_49.setGeometry(QtCore.QRect(150, 120, 501, 31))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.frame_11)
        self.label_50.setGeometry(QtCore.QRect(150, 160, 501, 31))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.frame_11)
        self.label_51.setGeometry(QtCore.QRect(40, 120, 91, 31))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.frame_11)
        self.label_52.setGeometry(QtCore.QRect(40, 160, 91, 31))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.frame_11)
        self.label_53.setGeometry(QtCore.QRect(40, 200, 91, 31))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame_11)
        self.label_54.setGeometry(QtCore.QRect(150, 200, 501, 31))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame_11)
        self.label_55.setGeometry(QtCore.QRect(150, 240, 501, 31))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.frame_11)
        self.label_56.setGeometry(QtCore.QRect(40, 240, 91, 31))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.frame_11)
        self.label_57.setGeometry(QtCore.QRect(40, 320, 91, 31))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_11)
        self.label_58.setGeometry(QtCore.QRect(150, 320, 501, 31))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame_11)
        self.label_59.setGeometry(QtCore.QRect(40, 280, 91, 31))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.frame_11)
        self.label_60.setGeometry(QtCore.QRect(150, 280, 501, 31))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.frame_11)
        self.label_61.setGeometry(QtCore.QRect(50, 455, 481, 31))
        self.label_61.setObjectName("label_61")
        self.stackedWidget.addWidget(self.pageSug)
        self.pageWeb = QtWidgets.QWidget()
        self.pageWeb.setObjectName("pageWeb")
        self.label_7 = QtWidgets.QLabel(self.pageWeb)
        self.label_7.setGeometry(QtCore.QRect(54, 20, 101, 31))
        self.label_7.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_7.setObjectName("label_7")
        self.pushButtonBli = QtWidgets.QPushButton(self.pageWeb)
        self.pushButtonBli.setGeometry(QtCore.QRect(60, 140, 121, 23))
        self.pushButtonBli.setObjectName("pushButtonBli")
        self.label_27 = QtWidgets.QLabel(self.pageWeb)
        self.label_27.setGeometry(QtCore.QRect(24, 24, 24, 24))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/icon/phres/icon/webpage.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.pushButtonWeb_2 = QtWidgets.QPushButton(self.pageWeb)
        self.pushButtonWeb_2.setGeometry(QtCore.QRect(60, 90, 121, 23))
        self.pushButtonWeb_2.setObjectName("pushButtonWeb_2")
        self.pushButtonBli_2 = QtWidgets.QPushButton(self.pageWeb)
        self.pushButtonBli_2.setGeometry(QtCore.QRect(60, 190, 121, 23))
        self.pushButtonBli_2.setObjectName("pushButtonBli_2")
        self.stackedWidget.addWidget(self.pageWeb)
        self.pageMe = QtWidgets.QWidget()
        self.pageMe.setObjectName("pageMe")
        self.label_8 = QtWidgets.QLabel(self.pageMe)
        self.label_8.setGeometry(QtCore.QRect(54, 20, 101, 31))
        self.label_8.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_8.setObjectName("label_8")
        self.pushButtonChangePas = QtWidgets.QPushButton(self.pageMe)
        self.pushButtonChangePas.setGeometry(QtCore.QRect(250, 25, 75, 23))
        self.pushButtonChangePas.setStyleSheet("")
        self.pushButtonChangePas.setObjectName("pushButtonChangePas")
        self.pushButtonfreshC = QtWidgets.QPushButton(self.pageMe)
        self.pushButtonfreshC.setGeometry(QtCore.QRect(160, 25, 75, 23))
        self.pushButtonfreshC.setObjectName("pushButtonfreshC")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.pageMe)
        self.stackedWidget_3.setGeometry(QtCore.QRect(30, 60, 691, 491))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_7 = QtWidgets.QFrame(self.page_3)
        self.frame_7.setGeometry(QtCore.QRect(0, 60, 321, 401))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frameMyCard_2 = QtWidgets.QFrame(self.frame_7)
        self.frameMyCard_2.setGeometry(QtCore.QRect(20, 30, 260, 330))
        self.frameMyCard_2.setMinimumSize(QtCore.QSize(260, 330))
        self.frameMyCard_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 55);\n"
"    border:none;\n"
"     font: 12pt \"幼圆\";\n"
"    color: rgb(108, 108, 108);\n"
"}\n"
"QPushButton{\n"
"    border-radius:20px;\n"
"    font: 10pt \"幼圆\";\n"
"    background-color: rgba(0, 170, 255,80);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(0, 170, 255,125);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QLabel{\n"
"    font: 9pt \"幼圆\";\n"
"}\n"
"#frameMyCard_2{\n"
"    border-top:2px solid gray;\n"
"    border-right:2px solid gray;\n"
"    border-left:1px solid gray;\n"
"    border-bottom:1px solid gray;\n"
"    border-color: rgba(181, 181, 181,100);\n"
"    border-bottom-color: rgba(181, 181, 181,60);\n"
"    border-left-color: rgba(181, 181, 181,60);\n"
"}")
        self.frameMyCard_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMyCard_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMyCard_2.setObjectName("frameMyCard_2")
        self.lineEditName_2 = QtWidgets.QLineEdit(self.frameMyCard_2)
        self.lineEditName_2.setGeometry(QtCore.QRect(50, 50, 200, 30))
        self.lineEditName_2.setInputMask("")
        self.lineEditName_2.setText("")
        self.lineEditName_2.setFrame(True)
        self.lineEditName_2.setPlaceholderText("")
        self.lineEditName_2.setObjectName("lineEditName_2")
        self.lineEditGender_2 = QtWidgets.QLineEdit(self.frameMyCard_2)
        self.lineEditGender_2.setGeometry(QtCore.QRect(50, 100, 200, 30))
        self.lineEditGender_2.setInputMask("")
        self.lineEditGender_2.setText("")
        self.lineEditGender_2.setPlaceholderText("")
        self.lineEditGender_2.setObjectName("lineEditGender_2")
        self.lineEditNumber_2 = QtWidgets.QLineEdit(self.frameMyCard_2)
        self.lineEditNumber_2.setGeometry(QtCore.QRect(50, 150, 200, 30))
        self.lineEditNumber_2.setInputMask("")
        self.lineEditNumber_2.setText("")
        self.lineEditNumber_2.setPlaceholderText("")
        self.lineEditNumber_2.setObjectName("lineEditNumber_2")
        self.lineEditEmail_2 = QtWidgets.QLineEdit(self.frameMyCard_2)
        self.lineEditEmail_2.setGeometry(QtCore.QRect(50, 200, 200, 30))
        self.lineEditEmail_2.setInputMask("")
        self.lineEditEmail_2.setText("")
        self.lineEditEmail_2.setPlaceholderText("")
        self.lineEditEmail_2.setObjectName("lineEditEmail_2")
        self.label_17 = QtWidgets.QLabel(self.frameMyCard_2)
        self.label_17.setGeometry(QtCore.QRect(10, 60, 54, 12))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frameMyCard_2)
        self.label_18.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frameMyCard_2)
        self.label_19.setGeometry(QtCore.QRect(10, 160, 54, 12))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frameMyCard_2)
        self.label_20.setGeometry(QtCore.QRect(10, 210, 54, 12))
        self.label_20.setObjectName("label_20")
        self.lineEditPart_2 = QtWidgets.QLineEdit(self.frameMyCard_2)
        self.lineEditPart_2.setGeometry(QtCore.QRect(50, 250, 200, 30))
        self.lineEditPart_2.setInputMask("")
        self.lineEditPart_2.setText("")
        self.lineEditPart_2.setPlaceholderText("")
        self.lineEditPart_2.setObjectName("lineEditPart_2")
        self.label_21 = QtWidgets.QLabel(self.frameMyCard_2)
        self.label_21.setGeometry(QtCore.QRect(10, 260, 54, 12))
        self.label_21.setObjectName("label_21")
        self.label_15 = QtWidgets.QLabel(self.frameMyCard_2)
        self.label_15.setGeometry(QtCore.QRect(100, 10, 54, 12))
        self.label_15.setObjectName("label_15")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_2.setGeometry(QtCore.QRect(340, 70, 311, 361))
        self.stackedWidget_2.setMinimumSize(QtCore.QSize(260, 330))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frameMyCard = QtWidgets.QFrame(self.page)
        self.frameMyCard.setGeometry(QtCore.QRect(30, 20, 260, 330))
        self.frameMyCard.setMinimumSize(QtCore.QSize(260, 330))
        self.frameMyCard.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 55);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"     font: 12pt \"幼圆\";\n"
"    color: rgb(108, 108, 108);\n"
"}\n"
"QPushButton{\n"
"    border-radius:20px;\n"
"    font: 10pt \"幼圆\";\n"
"    background-color: rgba(0, 170, 255,80);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(0, 170, 255,125);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QLabel{\n"
"font: 9pt \"幼圆\";\n"
"}\n"
"#frameMyCard{\n"
"    border-top:2px solid gray;\n"
"    border-right:2px solid gray;\n"
"    border-left:1px solid gray;\n"
"    border-bottom:1px solid gray;\n"
"    border-color: rgba(181, 181, 181,100);\n"
"    border-bottom-color: rgba(181, 181, 181,60);\n"
"    border-left-color: rgba(181, 181, 181,60);\n"
"}")
        self.frameMyCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMyCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMyCard.setObjectName("frameMyCard")
        self.label_9 = QtWidgets.QLabel(self.frameMyCard)
        self.label_9.setGeometry(QtCore.QRect(100, 10, 54, 12))
        self.label_9.setObjectName("label_9")
        self.lineEditName = QtWidgets.QLineEdit(self.frameMyCard)
        self.lineEditName.setGeometry(QtCore.QRect(50, 50, 200, 30))
        self.lineEditName.setInputMask("")
        self.lineEditName.setText("")
        self.lineEditName.setFrame(True)
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditGender = QtWidgets.QLineEdit(self.frameMyCard)
        self.lineEditGender.setGeometry(QtCore.QRect(50, 100, 200, 30))
        self.lineEditGender.setInputMask("")
        self.lineEditGender.setText("")
        self.lineEditGender.setObjectName("lineEditGender")
        self.lineEditNumber = QtWidgets.QLineEdit(self.frameMyCard)
        self.lineEditNumber.setGeometry(QtCore.QRect(50, 150, 200, 30))
        self.lineEditNumber.setInputMask("")
        self.lineEditNumber.setText("")
        self.lineEditNumber.setObjectName("lineEditNumber")
        self.lineEditEmail = QtWidgets.QLineEdit(self.frameMyCard)
        self.lineEditEmail.setGeometry(QtCore.QRect(50, 200, 200, 30))
        self.lineEditEmail.setInputMask("")
        self.lineEditEmail.setText("")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.label_10 = QtWidgets.QLabel(self.frameMyCard)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 54, 12))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frameMyCard)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frameMyCard)
        self.label_12.setGeometry(QtCore.QRect(10, 160, 54, 12))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frameMyCard)
        self.label_13.setGeometry(QtCore.QRect(10, 210, 54, 12))
        self.label_13.setObjectName("label_13")
        self.lineEditPart = QtWidgets.QLineEdit(self.frameMyCard)
        self.lineEditPart.setGeometry(QtCore.QRect(50, 250, 200, 30))
        self.lineEditPart.setInputMask("")
        self.lineEditPart.setText("")
        self.lineEditPart.setObjectName("lineEditPart")
        self.label_14 = QtWidgets.QLabel(self.frameMyCard)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 54, 12))
        self.label_14.setObjectName("label_14")
        self.pushButtonRefresh = QtWidgets.QPushButton(self.frameMyCard)
        self.pushButtonRefresh.setGeometry(QtCore.QRect(80, 295, 101, 23))
        self.pushButtonRefresh.setStyleSheet("border-radius:8px;")
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.stackedWidget_3.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_10 = QtWidgets.QFrame(self.page_5)
        self.frame_10.setGeometry(QtCore.QRect(20, 70, 481, 351))
        self.frame_10.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 55);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"     font: 12pt \"幼圆\";\n"
"    color: rgb(108, 108, 108);\n"
"}\n"
"QPushButton{\n"
"    border-radius:20px;\n"
"    font: 10pt \"幼圆\";\n"
"    background-color: rgba(0, 170, 255,80);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(0, 170, 255,125);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QLabel{\n"
"font: 9pt \"幼圆\";\n"
"}\n"
"#frameMyCard{\n"
"    border-top:2px solid gray;\n"
"    border-right:2px solid gray;\n"
"    border-left:1px solid gray;\n"
"    border-bottom:1px solid gray;\n"
"    border-color: rgba(181, 181, 181,100);\n"
"    border-bottom-color: rgba(181, 181, 181,60);\n"
"    border-left-color: rgba(181, 181, 181,60);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_42 = QtWidgets.QLabel(self.frame_10)
        self.label_42.setGeometry(QtCore.QRect(20, 120, 101, 41))
        self.label_42.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_42.setObjectName("label_42")
        self.label_41 = QtWidgets.QLabel(self.frame_10)
        self.label_41.setGeometry(QtCore.QRect(20, 80, 131, 20))
        self.label_41.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_41.setObjectName("label_41")
        self.label_40 = QtWidgets.QLabel(self.frame_10)
        self.label_40.setGeometry(QtCore.QRect(80, 20, 101, 31))
        self.label_40.setStyleSheet("font: 18pt \"幼圆\";")
        self.label_40.setObjectName("label_40")
        self.lineEditChangepas1 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEditChangepas1.setGeometry(QtCore.QRect(140, 80, 201, 20))
        self.lineEditChangepas1.setObjectName("lineEditChangepas1")
        self.lineEditChangepas2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEditChangepas2.setGeometry(QtCore.QRect(140, 130, 201, 20))
        self.lineEditChangepas2.setObjectName("lineEditChangepas2")
        self.pushButtonChangepascon = QtWidgets.QPushButton(self.frame_10)
        self.pushButtonChangepascon.setGeometry(QtCore.QRect(140, 190, 75, 23))
        self.pushButtonChangepascon.setStyleSheet("QPushButton{\n"
"    border-radius:8px;\n"
"    font: 10pt \"幼圆\";\n"
"    background-color: rgba(0, 170, 255,80);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(0, 170, 255,125);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pushButtonChangepascon.setObjectName("pushButtonChangepascon")
        self.stackedWidget_5 = QtWidgets.QStackedWidget(self.frame_10)
        self.stackedWidget_5.setGeometry(QtCore.QRect(59, 230, 251, 31))
        self.stackedWidget_5.setObjectName("stackedWidget_5")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_43 = QtWidgets.QLabel(self.page_6)
        self.label_43.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_43.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_43.setObjectName("label_43")
        self.stackedWidget_5.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_44 = QtWidgets.QLabel(self.page_7)
        self.label_44.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_44.setObjectName("label_44")
        self.stackedWidget_5.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_5.addWidget(self.page_8)
        self.stackedWidget_3.addWidget(self.page_5)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_39 = QtWidgets.QLabel(self.page_4)
        self.label_39.setGeometry(QtCore.QRect(20, 20, 171, 21))
        self.label_39.setStyleSheet("font: 14pt \"幼圆\";")
        self.label_39.setObjectName("label_39")
        self.stackedWidget_3.addWidget(self.page_4)
        self.label_28 = QtWidgets.QLabel(self.pageMe)
        self.label_28.setGeometry(QtCore.QRect(24, 24, 24, 24))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/icon/phres/icon/mypage.png"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.stackedWidget.addWidget(self.pageMe)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidgetCard.setCurrentIndex(0)
        self.stackedWidget_4.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_5.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "智能名片管理系统"))
        self.pushButtonHome.setText(_translate("MainWindow", "首页"))
        self.pushButtonCard.setText(_translate("MainWindow", "名片列表"))
        self.pushButtonEvent.setText(_translate("MainWindow", "事项清单"))
        self.pushButtonSug.setText(_translate("MainWindow", "更新日志"))
        self.pushButtonWeb.setText(_translate("MainWindow", "相关网页"))
        self.pushButtonMe.setText(_translate("MainWindow", "个人中心"))
        self.label_3.setText(_translate("MainWindow", "首页"))
        self.label_23.setText(_translate("MainWindow", "员工分布情况"))
        self.label_37.setText(_translate("MainWindow", "事项"))
        self.label_36.setText(_translate("MainWindow", "近期事项"))
        self.label_38.setText(_translate("MainWindow", "时间"))
        self.label_4.setText(_translate("MainWindow", "名片列表"))
        self.tabWidgetCard.setTabText(self.tabWidgetCard.indexOf(self.tab), _translate("MainWindow", "企业用户"))
        self.tabWidgetCard.setTabText(self.tabWidgetCard.indexOf(self.tab_2), _translate("MainWindow", "个人联系人"))
        self.label_16.setText(_translate("MainWindow", "删除联系人"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "输入联系人姓名"))
        self.label_22.setText(_translate("MainWindow", "搜索联系人"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "输入联系人姓名"))
        self.label_5.setText(_translate("MainWindow", "事项清单"))
        self.label_31.setText(_translate("MainWindow", "添加事项"))
        self.label_32.setText(_translate("MainWindow", "事件描述"))
        self.label_33.setText(_translate("MainWindow", "人员"))
        self.label_34.setText(_translate("MainWindow", "地点"))
        self.label_35.setText(_translate("MainWindow", "时间"))
        self.lineEditEventTime.setPlaceholderText(_translate("MainWindow", "格式：XXXX-XX-XX"))
        self.pushButtonEventAdd.setText(_translate("MainWindow", "添加事项"))
        self.label_6.setText(_translate("MainWindow", "更新日志"))
        self.label_45.setText(_translate("MainWindow", "2024/5/5"))
        self.label_46.setText(_translate("MainWindow", "修复已知bug（数据库表格排序问题等）"))
        self.label_47.setText(_translate("MainWindow", "2024/3/15"))
        self.label_48.setText(_translate("MainWindow", "更新事项清单功能"))
        self.label_49.setText(_translate("MainWindow", "UI，字体优化"))
        self.label_50.setText(_translate("MainWindow", "添加一件生成电子名片功能"))
        self.label_51.setText(_translate("MainWindow", "2024/3/15"))
        self.label_52.setText(_translate("MainWindow", "2024/3/15"))
        self.label_53.setText(_translate("MainWindow", "2024/3/15"))
        self.label_54.setText(_translate("MainWindow", "修复bug（搜索联系人无法显示）"))
        self.label_55.setText(_translate("MainWindow", "添加企业联系人分布图"))
        self.label_56.setText(_translate("MainWindow", "2024/3/15"))
        self.label_57.setText(_translate("MainWindow", "2024/3/15"))
        self.label_58.setText(_translate("MainWindow", "添加修改密码功能"))
        self.label_59.setText(_translate("MainWindow", "2024/3/15"))
        self.label_60.setText(_translate("MainWindow", "添加个人名片功能"))
        self.label_61.setText(_translate("MainWindow", "版本号信息 V0.0.1.5"))
        self.label_7.setText(_translate("MainWindow", "相关网站"))
        self.pushButtonBli.setText(_translate("MainWindow", "官方B站首页"))
        self.pushButtonWeb_2.setText(_translate("MainWindow", "企业官方网站"))
        self.pushButtonBli_2.setText(_translate("MainWindow", "官方微博"))
        self.label_8.setText(_translate("MainWindow", "个人中心"))
        self.pushButtonChangePas.setText(_translate("MainWindow", "修改密码"))
        self.pushButtonfreshC.setText(_translate("MainWindow", "更新名片"))
        self.label_17.setText(_translate("MainWindow", "姓名："))
        self.label_18.setText(_translate("MainWindow", "性别："))
        self.label_19.setText(_translate("MainWindow", "手机："))
        self.label_20.setText(_translate("MainWindow", "邮箱："))
        self.label_21.setText(_translate("MainWindow", "部门："))
        self.label_15.setText(_translate("MainWindow", "我的名片"))
        self.label_9.setText(_translate("MainWindow", "修改名片"))
        self.lineEditName.setPlaceholderText(_translate("MainWindow", "请输入姓名"))
        self.lineEditGender.setPlaceholderText(_translate("MainWindow", "请输入性别"))
        self.lineEditNumber.setPlaceholderText(_translate("MainWindow", "请输入手机号"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "请输入电子邮箱"))
        self.label_10.setText(_translate("MainWindow", "姓名："))
        self.label_11.setText(_translate("MainWindow", "性别："))
        self.label_12.setText(_translate("MainWindow", "手机："))
        self.label_13.setText(_translate("MainWindow", "邮箱："))
        self.lineEditPart.setPlaceholderText(_translate("MainWindow", "请输入部门"))
        self.label_14.setText(_translate("MainWindow", "部门："))
        self.pushButtonRefresh.setText(_translate("MainWindow", "更新我的名片"))
        self.label_42.setText(_translate("MainWindow", "确认密码"))
        self.label_41.setText(_translate("MainWindow", "请输入密码"))
        self.label_40.setText(_translate("MainWindow", "修改密码"))
        self.pushButtonChangepascon.setText(_translate("MainWindow", "确定"))
        self.label_43.setText(_translate("MainWindow", "密码不能为空"))
        self.label_44.setText(_translate("MainWindow", "修改成功"))
        self.label_39.setText(_translate("MainWindow", "欢迎来到个人中心！"))
import res_rc
