# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1094, 679)
        LoginWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcomeframe = QtWidgets.QFrame(self.centralwidget)
        self.Welcomeframe.setGeometry(QtCore.QRect(90, 80, 911, 441))
        self.Welcomeframe.setStyleSheet("#Welcomeframe{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20\n"
"}")
        self.Welcomeframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Welcomeframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Welcomeframe.setObjectName("Welcomeframe")
        self.WelcomeWord = QtWidgets.QLabel(self.Welcomeframe)
        self.WelcomeWord.setGeometry(QtCore.QRect(70, -20, 251, 101))
        self.WelcomeWord.setStyleSheet("font: 14pt \"幼圆\";")
        self.WelcomeWord.setObjectName("WelcomeWord")
        self.developers = QtWidgets.QLabel(self.Welcomeframe)
        self.developers.setGeometry(QtCore.QRect(50, 360, 461, 101))
        self.developers.setStyleSheet("font: 14pt \"幼圆\";")
        self.developers.setObjectName("developers")
        self.LandRframe = QtWidgets.QFrame(self.Welcomeframe)
        self.LandRframe.setGeometry(QtCore.QRect(490, 90, 350, 300))
        self.LandRframe.setMinimumSize(QtCore.QSize(350, 300))
        self.LandRframe.setStyleSheet("#LandRframe{\n"
"    border-top:2px solid gray;\n"
"    border-right:2px solid gray;\n"
"    border-left:1px solid gray;\n"
"    border-bottom:1px solid gray;\n"
"    border-radius:5px;\n"
"    border-color: rgba(181, 181, 181,100);\n"
"    border-bottom-color: rgba(181, 181, 181,60);\n"
"    border-left-color: rgba(181, 181, 181,60);\n"
"}\n"
"")
        self.LandRframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LandRframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LandRframe.setObjectName("LandRframe")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LandRframe)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.LandRframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(321, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidgetLoAndRe = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidgetLoAndRe.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 55);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"     font: 12pt \"幼圆\";\n"
"    color: rgb(108, 108, 108);\n"
"}\n"
"QPushButton{\n"
"    border-radius:20px;\n"
"    font: 12pt \"幼圆\";\n"
"    background-color: rgba(0, 170, 255,80);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 1px solid rgb(15 , 150 , 255);\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 1px solid rgb(1 , 84 , 153);\n"
"    background-color: rgba(0, 170, 255,125);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"")
        self.stackedWidgetLoAndRe.setObjectName("stackedWidgetLoAndRe")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(20, 20, 170, 32))
        self.label.setStyleSheet("font: 25 15pt \"微软雅黑 Light\";\n"
"color: rgb(11, 109, 255);")
        self.label.setObjectName("label")
        self.lineEditUserName = QtWidgets.QLineEdit(self.page)
        self.lineEditUserName.setGeometry(QtCore.QRect(20, 80, 250, 40))
        self.lineEditUserName.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditUserName.setStyleSheet("")
        self.lineEditUserName.setText("")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(self.page)
        self.lineEditPassword.setGeometry(QtCore.QRect(20, 130, 250, 40))
        self.lineEditPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditPassword.setStyleSheet("")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(self.page)
        self.pushButtonLogin.setGeometry(QtCore.QRect(20, 220, 111, 41))
        self.pushButtonLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonLogin.setStyleSheet("")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonToRe = QtWidgets.QPushButton(self.page)
        self.pushButtonToRe.setGeometry(QtCore.QRect(160, 220, 111, 41))
        self.pushButtonToRe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonToRe.setStyleSheet("")
        self.pushButtonToRe.setObjectName("pushButtonToRe")
        self.stackedWidgetLoAndRe.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 170, 32))
        self.label_2.setStyleSheet("font: 25 15pt \"微软雅黑 Light\";\n"
"color: rgb(11, 109, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEditReUserName = QtWidgets.QLineEdit(self.page_2)
        self.lineEditReUserName.setGeometry(QtCore.QRect(20, 60, 250, 40))
        self.lineEditReUserName.setText("")
        self.lineEditReUserName.setObjectName("lineEditReUserName")
        self.lineEditRePassword = QtWidgets.QLineEdit(self.page_2)
        self.lineEditRePassword.setGeometry(QtCore.QRect(20, 110, 250, 40))
        self.lineEditRePassword.setText("")
        self.lineEditRePassword.setObjectName("lineEditRePassword")
        self.lineEditReComfirm = QtWidgets.QLineEdit(self.page_2)
        self.lineEditReComfirm.setGeometry(QtCore.QRect(20, 160, 250, 40))
        self.lineEditReComfirm.setText("")
        self.lineEditReComfirm.setObjectName("lineEditReComfirm")
        self.pushButtonRe = QtWidgets.QPushButton(self.page_2)
        self.pushButtonRe.setGeometry(QtCore.QRect(20, 220, 111, 41))
        self.pushButtonRe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonRe.setStyleSheet("")
        self.pushButtonRe.setObjectName("pushButtonRe")
        self.pushButtonToLo = QtWidgets.QPushButton(self.page_2)
        self.pushButtonToLo.setGeometry(QtCore.QRect(160, 220, 111, 41))
        self.pushButtonToLo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonToLo.setStyleSheet("")
        self.pushButtonToLo.setAutoDefault(False)
        self.pushButtonToLo.setObjectName("pushButtonToLo")
        self.stackedWidgetLoAndRe.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidgetLoAndRe)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.label_3 = QtWidgets.QLabel(self.Welcomeframe)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 491, 341))
        self.label_3.setMinimumSize(QtCore.QSize(240, 240))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border：none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/pho/phres/login.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Welcomeframe)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icon/phres/icon/logintopleft.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.Welcomeframe)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 10, 32, 32))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-color: rgb(108, 108, 108);\n"
"    border-radius:50px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    border: 2px solid rgba(255, 0, 0, 200);\n"
"    background-color:rgba(255, 0, 0, 30);\n"
"    border-radius:16px;\n"
"}\n"
" \n"
"QPushButton:pressed\n"
"{\n"
"    border: 2px solid rgba(255, 0, 0, 200);\n"
"    background-color:rgba(255, 0, 0, 150);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"    border-radius:16px;\n"
"}")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/phres/icon/colse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.Welcomeframe)
        self.frame_3.setGeometry(QtCore.QRect(490, 390, 350, 36))
        self.frame_3.setMinimumSize(QtCore.QSize(350, 32))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setStyleSheet("font: 10pt \"幼圆\";\n"
"color: rgb(231, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageEmpty = QtWidgets.QWidget()
        self.pageEmpty.setObjectName("pageEmpty")
        self.stackedWidget.addWidget(self.pageEmpty)
        self.pageUserEmpty = QtWidgets.QWidget()
        self.pageUserEmpty.setObjectName("pageUserEmpty")
        self.label_5 = QtWidgets.QLabel(self.pageUserEmpty)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.pageUserEmpty)
        self.pageLoginFail = QtWidgets.QWidget()
        self.pageLoginFail.setObjectName("pageLoginFail")
        self.label_6 = QtWidgets.QLabel(self.pageLoginFail)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.pageLoginFail)
        self.pageReFail = QtWidgets.QWidget()
        self.pageReFail.setObjectName("pageReFail")
        self.label_7 = QtWidgets.QLabel(self.pageReFail)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.pageReFail)
        self.pagePassworddif = QtWidgets.QWidget()
        self.pagePassworddif.setObjectName("pagePassworddif")
        self.label_8 = QtWidgets.QLabel(self.pagePassworddif)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.pagePassworddif)
        self.pageReSuccess = QtWidgets.QWidget()
        self.pageReSuccess.setObjectName("pageReSuccess")
        self.label_9 = QtWidgets.QLabel(self.pageReSuccess)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 241, 16))
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.pageReSuccess)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.label_3.raise_()
        self.WelcomeWord.raise_()
        self.LandRframe.raise_()
        self.developers.raise_()
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.frame_3.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidgetLoAndRe.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.WelcomeWord.setText(_translate("LoginWindow", "智能名片管理系统"))
        self.developers.setText(_translate("LoginWindow", "成员名单：陈辰 佘张琦 黄睿涵 周弈晨"))
        self.label.setText(_translate("LoginWindow", "登录-Login"))
        self.lineEditUserName.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.lineEditPassword.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.pushButtonLogin.setText(_translate("LoginWindow", "登录"))
        self.pushButtonToRe.setText(_translate("LoginWindow", "跳转注册"))
        self.label_2.setText(_translate("LoginWindow", "注册-register"))
        self.lineEditReUserName.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.lineEditRePassword.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.lineEditReComfirm.setPlaceholderText(_translate("LoginWindow", "确认密码"))
        self.pushButtonRe.setText(_translate("LoginWindow", "注册"))
        self.pushButtonToLo.setText(_translate("LoginWindow", "返回登录"))
        self.label_5.setText(_translate("LoginWindow", "用户名和密码不能为空"))
        self.label_6.setText(_translate("LoginWindow", "用户不存在或密码错误"))
        self.label_7.setText(_translate("LoginWindow", "用户名已存在"))
        self.label_8.setText(_translate("LoginWindow", "两次输入密码不一致"))
        self.label_9.setText(_translate("LoginWindow", "注册成功，请返回登入"))
import res_rc
